package logging;

// Start of user code for imports
// End of user code

/**
 * Logger class definition.
 * Generated by the TouchCORE code generator.
 * 
 * This class is made by the user. It it required to be in this package.
 */
public class Logger{
	
    public static void log(String message) {
        System.out.println(message);
    }

}
